/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class fa_employee extends JFrame {

    /**
     * Creates new form fa_employee
     */
     Connection con;
       Statement ST;
       PreparedStatement ps;
       ResultSet rs;
     
      // Calendar  clndr1;
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    public fa_employee() {
        initComponents();
            try
        {
        
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);
            
            
    
           String qury="SELECT * FROM cinema.employee ";
             Statement ST2=con.createStatement(ResultSet .TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet   rs2=ST2.executeQuery(qury);
           DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            tblMod1.setRowCount(0);
            while (rs2.next()) 
            {
                 tblMod1.addRow(new String []{rs2.getString(2),rs2.getString(1),rs2.getString(3),rs2.getString(9),rs2.getString(5),rs2.getString(4),rs2.getString(6),rs2.getString(7)});
            } 
         
          
            System.out.println("ddddd");
        
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "connected");
            
       }
        
      catch(Exception ex )
       {
            System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(null , " not connected");
              
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        refresh_ALL = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "ID", "BAIRTH DATE", "Address", "Salary", "phone_number", "Working_Days", "working hours "
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 37, 550, 130));

        refresh_ALL.setIcon(new ImageIcon("C:\\Users\\hp\\Downloads\\cinema\\cinema4\\src\\pic\\Refresh-Icon (1).png")
        );
        refresh_ALL.setPreferredSize(new java.awt.Dimension(20, 20));
        refresh_ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_ALLActionPerformed(evt);
            }
        });
        jPanel1.add(refresh_ALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 177, 40, 30));

        update.setBackground(new java.awt.Color(172, 0, 0));
        update.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 237, 100, -1));

        delete.setBackground(new java.awt.Color(172, 0, 0));
        delete.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 267, 100, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 187, 37, -1));

        jTextField9.setBackground(new java.awt.Color(172, 0, 0));
        jTextField9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 187, 110, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 217, 30, -1));

        jTextField10.setBackground(new java.awt.Color(172, 0, 0));
        jTextField10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 217, 108, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("BirthDate");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 247, -1, -1));

        jTextField17.setBackground(new java.awt.Color(172, 0, 0));
        jTextField17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 247, 108, -1));

        jLabel18.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ADDRES");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 277, 60, -1));

        jTextField12.setBackground(new java.awt.Color(172, 0, 0));
        jTextField12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 277, 110, -1));

        jLabel21.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Salary");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 317, 40, -1));

        jTextField11.setBackground(new java.awt.Color(172, 0, 0));
        jTextField11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 317, 110, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone Number");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 347, 91, -1));

        jTextField15.setBackground(new java.awt.Color(172, 0, 0));
        jTextField15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 347, 110, -1));

        jLabel19.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Working Days");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 377, -1, -1));

        jTextField16.setBackground(new java.awt.Color(172, 0, 0));
        jTextField16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 377, 112, -1));

        jTextField13.setBackground(new java.awt.Color(172, 0, 0));
        jTextField13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 407, 112, -1));

        jLabel20.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Working Hours");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 417, 98, -1));

        add.setBackground(new java.awt.Color(172, 0, 0));
        add.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema4_1\\cinema4\\src\\pic\\hall (1).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
        int index=jTable1.getSelectedRow();
        if (index != -1 && index < tblMod1.getRowCount())
        {

            String  name=tblMod1.getValueAt(index, 0).toString();
            String  ID=tblMod1.getValueAt(index, 1).toString();
            String Bdate = tblMod1.getValueAt(index, 2).toString();
            //   Date Bdate1 = java.sql.Date.valueOf(Bdate);

            String  Address=tblMod1.getValueAt(index, 3).toString();
            String  Salary=tblMod1.getValueAt(index, 4).toString();
            String  phone_number=tblMod1.getValueAt(index, 5).toString();
            String  Working_Days=tblMod1.getValueAt(index, 6).toString();
            String working_hours  =tblMod1.getValueAt(index, 7).toString();

            jTextField9.setText(name);
            jTextField10.setText(ID);

            //  clndr1.setTime(Bdate1);
            //  jCalendar3.setCalendar(clndr1);
            jTextField17.setText(Bdate);
            jTextField12.setText(Address);
            jTextField11.setText(Salary);
            jTextField15.setText(phone_number);
            jTextField16.setText(Working_Days);
            jTextField13.setText(working_hours);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void refresh_ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_ALLActionPerformed
        try{

            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            String qury2="SELECT *FROM cinema.employee ";
            System.out.println(qury2);
            Statement  STR=con.createStatement();
            ResultSet  Rrs= STR.executeQuery(qury2);
            DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            tblMod1.setRowCount(0);
             while (Rrs.next()) 
            {
                 tblMod1.addRow(new String []{Rrs.getString(2),Rrs.getString(1),Rrs.getString(3),Rrs.getString(9),Rrs.getString(5),Rrs.getString(4),Rrs.getString(6),Rrs.getString(7)});
            } 
         
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField17.setText("");
            jTextField12.setText("");
            jTextField11.setText("");
            jTextField15.setText("");
            jTextField16.setText("");
            jTextField13.setText("");

            con.commit();
            con.close();
        }
        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_refresh_ALLActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String name=jTextField9.getText();
        String id=jTextField10.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        // String bdate = dateFormat.format(jCalendar3.getCalendar().getTime());
        String bdate=jTextField17.getText();
        String addres=jTextField12.getText();
        int salary= Integer.parseInt(jTextField11.getText());
        String phone= jTextField15.getText();
        String days=jTextField16.getText();          /////////////////////////
        int hoursx= Integer.parseInt( jTextField13.getText());

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            String qury2="UPDATE cinema.employee set ename=?, ebirthday=?, eaddress=?, ephone_num=?,eworking_days=?  where( eid=?)";
            
            ps=con .prepareStatement(qury2);

            ps.setString(1, name);
            //  ps.setString(2, id);
            ps.setDate(2, java.sql.Date.valueOf(bdate));
            ps.setString(3, addres);
           // ps.setInt(4, salary);
            ps.setString(4, phone);
            ps.setString(5,days);
            //  ps.setInt(7,hoursx);
            ps.setString(6, id);
            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "connected");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }

    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            int index=jTable1.getSelectedRow();

            String  ID=tblMod1.getValueAt(index, 1).toString();

            String qury2="DELETE FROM cinema.employee  where( eid=?)";
            ps=con .prepareStatement(qury2);
            ps.setString(1, ID);

            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "connected");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }

    }//GEN-LAST:event_deleteActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed

    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String name=jTextField9.getText();
        String id=jTextField10.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //String bdate = dateFormat.format(jCalendar3.getCalendar().getTime());
        String bdate=jTextField17.getText();
        String addres=jTextField12.getText();
        int salary= Integer.parseInt(jTextField11.getText());
        String phone= jTextField15.getText();
        String days=jTextField16.getText();          /////////////////////////
        int hoursx= Integer.parseInt( jTextField13.getText());

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            //ename=?, ebirthday=?, eaddress=?, esalary=?, ephone_num=?,eworking_days
            String qury2="INSERT INTO cinema.employee (eid,ename,  ebirthday,ephone_num, eworking_days,eworking_hours,eaddress  ) VALUES ( ?, ?,?,?,?,?,?)";
            ps=con .prepareStatement(qury2);

          
            /////////////////////////
             ps.setString(1, id);
             ps.setString(2, name);
            ps.setDate(3, java.sql.Date.valueOf(bdate));
            ps.setString(4, phone);
           // ps.setInt(5, salary); 
            ps.setString(5,days);
            ps.setInt(6,hoursx);
            ps.setString(7, addres);
        
            
            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "Done");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }

    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fa_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fa_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fa_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fa_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fa_employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton refresh_ALL;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
