/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class fa_hall extends javax.swing.JFrame {
   Connection con;
       Statement ST;
       PreparedStatement ps;
       ResultSet rs;
    /**
     * Creates new form fa_hall
     */
    public fa_hall() {
        initComponents();
         
         try 
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);
            
            String qury="SELECT *FROM cinema.hall ";
           System.out.println(qury);
          
           
            ST=con.createStatement();
            rs= ST.executeQuery(qury);
           
           
            DefaultTableModel tblModl = (DefaultTableModel) jTable1.getModel();
            tblModl.setRowCount(0);
           
            while (rs.next()) 
            {
                 tblModl.addRow(new String []{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
           
            con.commit();
            con.close();
           // JOptionPane.showMessageDialog(null , "connected");
            
       }
        
      catch(Exception ex )
      {
            System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(null , " not connected");
              
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        refresh_ALL = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("id number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));

        jTextField1.setBackground(new java.awt.Color(172, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 210, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("reservation_times");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, -1));

        jTextField2.setBackground(new java.awt.Color(172, 0, 0));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 210, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("number_of_seats");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, -1));

        jTextField3.setBackground(new java.awt.Color(172, 0, 0));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 210, -1));

        add.setBackground(new java.awt.Color(172, 0, 0));
        add.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        update.setBackground(new java.awt.Color(172, 0, 0));
        update.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 100, -1));

        delete.setBackground(new java.awt.Color(172, 0, 0));
        delete.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 90, -1));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "reservation_times", "number_of_seats"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 340, 110));

        refresh_ALL.setIcon(new ImageIcon("C:\\Users\\hp\\Downloads\\cinema\\cinema4\\src\\pic\\Refresh-Icon (1).png")
        );
        refresh_ALL.setPreferredSize(new java.awt.Dimension(20, 20));
        refresh_ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_ALLActionPerformed(evt);
            }
        });
        jPanel1.add(refresh_ALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 30, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\hallA (1).png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String id=jTextField1.getText();
        String Rtime=jTextField2.getText();
        int seat =Integer.parseInt(jTextField3.getText());

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            String qury2="INSERT INTO cinema.hall(hid, hreservation_time,hnum_of_seats ) VALUES (?,?,?)";
            ps=con .prepareStatement(qury2);

            ps.setString(1, id);
            ps.setString(2, Rtime);
            ps.setInt(3, seat);

            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "ADDED");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String id=jTextField1.getText();
        String Rtime=jTextField2.getText();
        int seat=Integer.parseInt(jTextField3.getText());

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            String qury2="UPDATE cinema.hall set  hid=?,hreservation_time=?,hnum_of_seats=? where( hid=?)";
            ps=con .prepareStatement(qury2);

            ps.setString(1, id);
            ps.setString(2, Rtime);
            ps.setInt(3, seat);
            ps.setString(4, id);
            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "DONE");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            int index=jTable1.getSelectedRow();

            String  ID=tblMod1.getValueAt(index, 0).toString();

            String qury2="DELETE FROM cinema.hall  where( hid=?)";
            ps=con .prepareStatement(qury2);
            ps.setString(1, ID);

            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "DONE");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
        int index=jTable1.getSelectedRow();
        if (index != -1 && index < tblMod1.getRowCount())
        {

            String  ID=tblMod1.getValueAt(index, 0).toString();
            String  RTIME=tblMod1.getValueAt(index, 1).toString();
            String NUM_SEAT=tblMod1.getValueAt(index, 2).toString();

            jTextField1.setText(ID);
            jTextField2.setText(RTIME);
            jTextField3.setText(NUM_SEAT);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

    }//GEN-LAST:event_jTable1KeyPressed

    private void refresh_ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_ALLActionPerformed
        try{

            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con.setAutoCommit(false);

            String qury="SELECT * FROM cinema.hall  ";
            ST=con.createStatement(ResultSet .TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs2=ST.executeQuery(qury);
            DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            tblMod1.setRowCount(0);
            while (rs2.next())
            {
                tblMod1.addRow(new String []{rs2.getString(1),rs2.getString(2),rs2.getString(3)});
            }

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");

            con.commit();
            con.close();
        }
        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_refresh_ALLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fa_hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fa_hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fa_hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fa_hall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fa_hall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton refresh_ALL;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
