/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class fa_ticket extends javax.swing.JFrame {
  Connection con;
       Statement ST;
       PreparedStatement ps;
       ResultSet rs;
       SimpleDateFormat dateFormatDD = new SimpleDateFormat("yyyy-MM-dd");
       SimpleDateFormat dateFormatTT = new SimpleDateFormat("HH:mm:ss");
    /**
     * Creates new form fa_ticket
     */
    public fa_ticket() {
        initComponents();
           try
        {
        
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
             con =DriverManager.getConnection(conninfo,"dialaa","12345");
             con .setAutoCommit(false);
            
            
    
           String qury="SELECT * FROM cinema.ticket  ";
            ST=con.createStatement(ResultSet .TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
             rs=ST.executeQuery(qury);
           DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            tblMod1.setRowCount(0);
            while (rs.next()) 
            {
                 tblMod1.addRow(new String []{rs.getString(2),rs.getString(1),rs.getString(3),rs.getString(11),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(4),rs.getString(8),rs.getString(9),rs.getString(10)});
            } 
         
          
           
        
            con.commit();
            con.close();
           // JOptionPane.showMessageDialog(null , "connected");
            
       }
        
      catch(Exception ex )
       {
            System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(null , " not connected");
              
       }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        refresh_ALL = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText(" NAME:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 70, 20));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 160, 20));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 45, 160, 20));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, 20));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("DATE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 75, 50, 20));

        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, 160, 20));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("HALL NUM:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 80, 20));

        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, 160, 20));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("PRICE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 135, 50, 20));

        jTextField5.setBackground(new java.awt.Color(51, 51, 51));
        jTextField5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 135, 160, 20));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("SEAT NUM:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 80, 20));

        jTextField6.setBackground(new java.awt.Color(51, 51, 51));
        jTextField6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 165, 160, 20));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("REMANING:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 90, 20));

        jTextField7.setBackground(new java.awt.Color(51, 51, 51));
        jTextField7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 195, 160, 20));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("TIME:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, 60, 20));

        jTextField8.setBackground(new java.awt.Color(51, 51, 51));
        jTextField8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 225, 160, 20));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("MOVIE ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 90, 20));

        jTextField9.setBackground(new java.awt.Color(51, 51, 51));
        jTextField9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 255, 160, 20));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("EMP ID:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 285, 60, 20));

        jTextField10.setBackground(new java.awt.Color(51, 51, 51));
        jTextField10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 285, 160, 20));

        jTextField11.setBackground(new java.awt.Color(51, 51, 51));
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 315, 160, 20));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("c_gamil:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 315, 60, 20));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "ID", "DATE", "HALL NUMBER", "PRICE", "SEAT NUMBER", "REMAINING NUMBER", "TIME ", "MOVIE ID", "EMPLOYEE ID ", "c_gamil"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 345, 570, 140));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 315, 90, -1));

        refresh_ALL.setIcon(new ImageIcon("C:\\Users\\hp\\Downloads\\cinema\\cinema4\\src\\pic\\Refresh-Icon (1).png")
        );
        refresh_ALL.setPreferredSize(new java.awt.Dimension(20, 20));
        refresh_ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_ALLActionPerformed(evt);
            }
        });
        jPanel1.add(refresh_ALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 45, 40, 30));

        add.setBackground(new java.awt.Color(172, 0, 0));
        add.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 15, 80, -1));

        update.setBackground(new java.awt.Color(172, 0, 0));
        update.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 15, 90, -1));

        delete.setBackground(new java.awt.Color(172, 0, 0));
        delete.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 15, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\TICKETA2 (1).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
        int index=jTable1.getSelectedRow();
        if (index != -1 && index < tblMod1.getRowCount())
        {

            String  name=tblMod1.getValueAt(index, 0).toString();
            String  ID=tblMod1.getValueAt(index, 1).toString();
            String date = tblMod1.getValueAt(index, 2).toString();
            String  hall_num=tblMod1.getValueAt(index, 3).toString();
            String  price=tblMod1.getValueAt(index, 4).toString();
            String seat=tblMod1.getValueAt(index, 5).toString();
            String  remainig=tblMod1.getValueAt(index, 6).toString();
            String time =tblMod1.getValueAt(index, 7).toString();
            String m_id  =tblMod1.getValueAt(index, 8).toString();
            String e_id  =tblMod1.getValueAt(index, 9).toString();
            String c_gamil=tblMod1.getValueAt(index, 10).toString();

            jTextField1.setText(name);
            jTextField2.setText(ID);
            jTextField3.setText(date);
            jTextField4.setText(hall_num);
            jTextField5.setText(price);
            jTextField6.setText(seat);
            jTextField7.setText(remainig);
            jTextField8.setText(time);
            jTextField9.setText(m_id);
            jTextField10.setText(e_id);
            jTextField11.setText(c_gamil);

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        fa2 f =new fa2();

        f9.setVisible(Boolean.TRUE);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void refresh_ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_ALLActionPerformed
        try{

            DriverManager.registerDriver(new  org.postgresql.Driver());
           String conninfo="jdbc:postgresql://localhost:5432/postgres";
             con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con.setAutoCommit(false);

            String qury="SELECT * FROM cinema.ticket  ";
            ST=con.createStatement(ResultSet .TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs2=ST.executeQuery(qury);
            DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            tblMod1.setRowCount(0);
            while (rs2.next())
            {
                 tblMod1.addRow(new String []{rs.getString(2),rs.getString(1),rs.getString(3),rs.getString(11),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(4),rs.getString(8),rs.getString(9),rs.getString(10)});
            }

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");

            con.commit();
            con.close();
        }
        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_refresh_ALLActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String name=jTextField1.getText();
        String id=jTextField2.getText();
        String date=jTextField3.getText();
        int  hall_num= Integer.parseInt(jTextField4.getText());
        int price= Integer.parseInt(jTextField5.getText());
        int  seat= Integer.parseInt (jTextField6.getText());
        int remaning= Integer.parseInt(jTextField7.getText());
        String time= jTextField8.getText(); ////////////////////////
        String m_id=  jTextField9.getText();
        String e_id=  jTextField10.getText();
        String c_gamil= jTextField11.getText();
        // Date parsedDate = dateFormatTT.parse(time);
        //  Time sqlTime = new Time(parsedDate.getTime());

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
          String conninfo="jdbc:postgresql://localhost:5432/postgres";
             con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            String qury2="INSERT INTO cinema.ticket (tname_of_movie, tidd, tdate,hall_num, tprice,tseats_num,tremaining_Seats_num,mid,eid,cgmail ) VALUES (?, ?,?,?,?,?,?,?,?,?)";
            ps=con .prepareStatement(qury2);

            ps.setString(1, name);
            ps.setString(2, id);
            ps.setDate(3, java.sql.Date.valueOf(date));
            ps.setInt(4, hall_num);
            ps.setInt(5, price);
            ps.setInt(6, seat);
            ps.setInt(7,remaning);
            // ps.setTime(8,sqlTime);
            ps.setString(8,m_id);
            ps.setString(9,e_id);
            ps.setString(10,c_gamil);
            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "ADDED");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String name=jTextField1.getText();
        String id=jTextField2.getText();
        String date=jTextField3.getText();
        int  hall_num= Integer.parseInt(jTextField4.getText());
        int price= Integer.parseInt(jTextField5.getText());
        int  seat= Integer.parseInt (jTextField6.getText());
        int remaning= Integer.parseInt(jTextField7.getText());
        String time= jTextField8.getText(); ////////////////////////
        String m_id=  jTextField9.getText();
        String e_id=  jTextField10.getText();
        String c_gamil= jTextField11.getText();

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
           String conninfo="jdbc:postgresql://localhost:5432/postgres";
             con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            String qury2="UPDATE cinema.ticket set tname_of_movie=?, tidd=?, tdate=?,hall_num=?, tprice=?,tseats_num=?,tremaining_Seats_num=?,mid=?,eid=?,cgmail=? where( tidd=?)";
            ps=con .prepareStatement(qury2);

            ps.setString(1, name);
            ps.setString(2, id);
            ps.setDate(3, java.sql.Date.valueOf(date));
            ps.setInt(4, hall_num);
            ps.setInt(5, price);
            ps.setInt(6, seat);
            ps.setInt(7,remaning);
            // ps.setTime(8,sqlTime);
            ps.setString(8,m_id);
            ps.setString(9,e_id);
            ps.setString(10,c_gamil);
            ps.setString(11, id);
            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "DONE");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try
        {
            DriverManager.registerDriver(new  org.postgresql.Driver());
          String conninfo="jdbc:postgresql://localhost:5432/postgres";
             con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);

            DefaultTableModel tblMod1 = (DefaultTableModel) jTable1.getModel();
            int index=jTable1.getSelectedRow();

            String  ID=tblMod1.getValueAt(index, 2).toString();

            String qury2="DELETE FROM cinema.ticket  where( tidd=?)";
            ps=con .prepareStatement(qury2);
            ps.setString(1, ID);

            ps .executeUpdate();
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null , "DONE");

        }

        catch(Exception ex )
        {

            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null , " not connected");

        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fa_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fa_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fa_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fa_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fa_ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton refresh_ALL;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
