/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import static com.mycompany.cinema.user_f_movie1.t1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class juiu extends JFrame {
  Connection con;
       Statement ST;
       ResultSet rs;
    
    /**
     * Creates new form juiu
     */
    public juiu() {
        initComponents();
        
        
         try
         {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);
            
            
        String qury2="SELECT * FROM cinema.snack ";
            ST=con.createStatement(ResultSet .TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            rs=ST.executeQuery(qury2);
        
      while(rs.next()){ 


            
            
          //    l1.setText(p); 
          int id=rs.getInt("sid");
          if(id==800){
              String  p=rs.getString(3);
            this.l1.setText(p);}
            
          else if(id==801){
              String  p=rs.getString(3);
            this.l2.setText(p);}
     
       else if(id==802){
              String  p=rs.getString(3);
            this.l3.setText(p);}
       else if(id==803){
              String  p=rs.getString(3);
            this.l4.setText(p);}
       else if(id==804){
              String  p=rs.getString(3);
            this.l5.setText(p);}
       else if(id==805){
              String  p=rs.getString(3);
            this.l6.setText(p);}
     
         }
       
            
            con.commit();
            con.close();
          
          
            
         }
        catch(Exception ex )
      {
            System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(null , " not connected");
              
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        s6 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        s5 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        s3 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        s4 = new javax.swing.JSpinner();
        s2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        s1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\pin.png")); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\ora.png")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\man (2).png")); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 110, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\lem (1).png")); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\gra (2).png")); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, 130));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\app (2).png")); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, 120, 110));

        jLabel17.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel17.setText("JUICE");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel5.setText("...........................................APPLE JUICE");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 700, 340, 30));

        s6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s6.setToolTipText("");
        jPanel3.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 760, 80, 30));

        jLabel7.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel7.setText("LEMON JUICE .....................................................");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 400, -1));

        l6.setText("jLabel9");
        jPanel3.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 730, 50, -1));

        l1.setText("l1");
        jPanel3.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 50, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel8.setText("...........................................ORANGE JUICE");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 360, 30));

        l2.setText("l2");
        jPanel3.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 50, -1));

        jButton1.setBackground(new java.awt.Color(252, 219, 225));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jButton1.setText("Confirm the order ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 800, 170, -1));

        s5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s5.setToolTipText("");
        jPanel3.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 80, 30));

        jLabel4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel4.setText("...........................................GRAPS JUICE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 330, -1));

        s3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s3.setToolTipText("");
        jPanel3.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 80, 30));

        jLabel6.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel6.setText("MANGO JUICE .....................................................");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 400, -1));

        jLabel18.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel18.setText("you want");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        l5.setText("jLabel9");
        jPanel3.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 50, -1));

        s4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s4.setToolTipText("");
        jPanel3.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 80, 30));

        s2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s2.setToolTipText("");
        jPanel3.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 80, 30));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel19.setText("Here you can choose the type of any juice that suits you, and you can also choose the quantity ");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 570, -1));

        l4.setText("jLabel9");
        jPanel3.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 50, -1));

        l3.setText("l3");
        jPanel3.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 50, -1));

        s1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s1.setToolTipText("");
        jPanel3.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, 30));

        jLabel2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel2.setText("PINEAPPLE JUICE ..................................................");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 400, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\bbbaaaccckkk (1).png")); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\bbbaaaccckkk (1).png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 600, 340));

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ans;
        int n1,n2,n3,n4,n5,n6;
        
        n1=(int)s1.getValue();
        String n11=l1.getText();
       int n111=Integer.parseInt(n11);
       int n1111=n1*n111;
       
        n2=(int)s2.getValue();
         String n22=l2.getText();
       int n222=Integer.parseInt(n22);
       int n2222=n2*n222;
       
        n3=(int)s3.getValue();
         String n33=l3.getText();
       int n333=Integer.parseInt(n33);
       int n3333=n3*n333;
       
        n4=(int)s4.getValue();
         String n44=l4.getText();
       int n444=Integer.parseInt(n44);
       int n4444=n4*n444;
       
        n5=(int)s5.getValue();
         String n55=l5.getText();
       int n555=Integer.parseInt(n55);
       int n5555=n5*n555;
       
        n6=(int)s6.getValue();
         String n66=l6.getText();
       int n666=Integer.parseInt(n66);
       int n6666=n6*n666;
        
        ans=n1111+n2222+n3333+n4444+n5555+n6666;
      JOptionPane.showMessageDialog(null, ans);
    /*    if(n2==0&&n3==0&&n4==0&&n5==0&&n6==0){//n1
            ans=n1111; JOptionPane.showMessageDialog(null, ans);
        }else if(n1==0&&n3==0&&n4==0&&n5==0&&n6==0){//n2
            ans=n2222; JOptionPane.showMessageDialog(null, ans);
        }else if(n2==0&&n1==0&&n4==0&&n5==0&&n6==0){//n3
            ans=n3333; JOptionPane.showMessageDialog(null, ans);
        }
        else if(n2==0&&n3==0&&n1==0&&n5==0&&n6==0){//n4
            ans=n4444; JOptionPane.showMessageDialog(null, ans);
        }else if(n2==0&&n3==0&&n4==0&&n1==0&&n6==0){//n5
            ans=n5555; JOptionPane.showMessageDialog(null, ans);
        }else if(n2==0&&n3==0&&n4==0&&n5==0&&n1==0){
            ans=n6666; JOptionPane.showMessageDialog(null, ans);
        }*/
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juiu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JSpinner s1;
    private javax.swing.JSpinner s2;
    private javax.swing.JSpinner s3;
    private javax.swing.JSpinner s4;
    private javax.swing.JSpinner s5;
    private javax.swing.JSpinner s6;
    // End of variables declaration//GEN-END:variables
}
