/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class piu extends JFrame {
 Connection con;
       Statement ST;
       ResultSet rs;
    
    /**
     * Creates new form piu
     */
    public piu() {
        initComponents();
        
         try
         {
            DriverManager.registerDriver(new  org.postgresql.Driver());
            String conninfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con =DriverManager.getConnection(conninfo,"dialaa","12345");
            con .setAutoCommit(false);
            
            
        String qury2="SELECT * FROM cinema.snack ";
            ST=con.createStatement(ResultSet .TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            rs=ST.executeQuery(qury2);
        
      while(rs.next()){ 


            
            
          //    l1.setText(p); 
          int id=rs.getInt("sid");
          if(id==600){
              String  p=rs.getString(3);
            this.l1.setText(p);}
            
          else if(id==601){
              String  p=rs.getString(3);
            this.l2.setText(p);}
     
       else if(id==602){
              String  p=rs.getString(3);
            this.l3.setText(p);}
       else if(id==603){
              String  p=rs.getString(3);
            this.l4.setText(p);}
       else if(id==604){
              String  p=rs.getString(3);
            this.l5.setText(p);}
       else if(id==605){
              String  p=rs.getString(3);
            this.l6.setText(p);}
     
          else if(id==606){
              String  p=rs.getString(3);
            this.l11.setText(p);}
          else if(id==607){
              String  p=rs.getString(3);
            this.l111.setText(p);}
          
          else if(id==608){
              String  p=rs.getString(3);
            this.l22.setText(p);}
          else if(id==609){
              String  p=rs.getString(3);
            this.l222.setText(p);} 
          
          else if(id==610){
              String  p=rs.getString(3);
            this.l33.setText(p);}
          else if(id==611){
              String  p=rs.getString(3);
            this.l333.setText(p);}
          
           else if(id==612){
              String  p=rs.getString(3);
            this.l44.setText(p);}
          else if(id==613){
              String  p=rs.getString(3);
            this.l444.setText(p);}
          
           else if(id==614){
              String  p=rs.getString(3);
            this.l55.setText(p);}
          else if(id==615){
              String  p=rs.getString(3);
            this.l555.setText(p);}
          
           else if(id==616){
              String  p=rs.getString(3);
            this.l66.setText(p);}
          else if(id==617){
              String  p=rs.getString(3);
            this.l666.setText(p);}
         }
       
            
            con.commit();
            con.close();
          
          
            
         }
        catch(Exception ex )
      {
            System.out.println(ex.getMessage());
          JOptionPane.showMessageDialog(null , " not connected");
              
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        s3 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        s4 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        s2 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        s1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        s5 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        s6 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l111 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l222 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l333 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l444 = new javax.swing.JLabel();
        l555 = new javax.swing.JLabel();
        l44 = new javax.swing.JLabel();
        l666 = new javax.swing.JLabel();
        l66 = new javax.swing.JLabel();
        l55 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\sal (4).png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 810, 130, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\mas.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, -1));

        jLabel19.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel19.setText("Here you can choose the type of pizza that suits you, and you can also choose the quantity ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 570, -1));

        jLabel18.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel18.setText("you want");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        jRadioButton1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton1.setText("LARGE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton2.setText("SMALL");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton3.setText("MEDIUM");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton4.setText("SMALL");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jRadioButton5.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton5.setText("MEDIUM");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jRadioButton6.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton6.setText("LARGE");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jRadioButton7.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton7.setText("SMALL");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        jRadioButton8.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton8.setText("MEDIUM");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        jRadioButton9.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton9.setText("LARGE");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("Quantity to order");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 120, -1));

        s3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s3.setToolTipText("");
        jPanel2.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 130, 30));

        jLabel16.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel16.setText("CAPRICCIO PIZZA .............................................");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 400, -1));

        jRadioButton10.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton10.setText("SMALL");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, -1, -1));

        jRadioButton11.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton11.setText("MEDIUM");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, -1, -1));

        jRadioButton12.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton12.setText("LARGE");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 730, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setText("Quantity to order");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 680, 120, -1));

        s4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s4.setToolTipText("");
        jPanel2.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 710, 130, 30));

        jLabel14.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel14.setText("........................................... JALAPENO PIZZA");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 390, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("Quantity to order");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 120, -1));

        s2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s2.setToolTipText("");
        jPanel2.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 130, 30));

        jLabel12.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel12.setText("...........................................VEGETABLES PIZZA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 390, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel11.setText("MUSHROOM PIZZA .............................................");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 400, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Quantity to order");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 120, -1));

        s1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s1.setToolTipText("");
        jPanel2.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 30));

        jLabel20.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel20.setText("........................................... SALAMI PIZZA");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 810, 390, -1));

        jRadioButton13.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton13.setText("SMALL");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 850, -1, -1));

        jRadioButton14.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton14.setText("MEDIUM");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 880, -1, -1));

        jRadioButton15.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton15.setText("LARGE");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 910, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setText("Quantity to order");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 860, 120, -1));

        s5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s5.setToolTipText("");
        jPanel2.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 890, 130, 30));

        jLabel23.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel23.setText("CHEESE PIZZA ..........................................");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 980, 400, -1));

        jRadioButton16.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton16.setText("SMALL");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1020, -1, -1));

        jRadioButton17.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton17.setText("MEDIUM");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1050, -1, -1));

        jRadioButton18.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jRadioButton18.setText("LARGE");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1080, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel24.setText("Quantity to order");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 1030, 120, -1));

        s6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        s6.setToolTipText("");
        jPanel2.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 1060, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\jal.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 120, -1));

        l5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l5.setText("jLabel25");
        jPanel2.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 850, -1, -1));

        l6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l6.setText("jLabel25");
        jPanel2.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1020, -1, -1));

        l3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l3.setText("jLabel25");
        jPanel2.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, 20));

        l2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l2.setText("jLabel25");
        jPanel2.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        l111.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l111.setText("jLabel25");
        jPanel2.add(l111, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 150, 40));

        l4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l4.setText("jLabel25");
        jPanel2.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, -1));

        l11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l11.setText("jLabel25");
        jPanel2.add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 150, 40));

        l222.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l222.setText("jLabel25");
        jPanel2.add(l222, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        l22.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l22.setText("jLabel25");
        jPanel2.add(l22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel9.setText("PIZZA");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 120, -1));

        l333.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l333.setText("jLabel25");
        jPanel2.add(l333, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, 20));

        l33.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l33.setText("jLabel25");
        jPanel2.add(l33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, 20));

        jButton1.setBackground(new java.awt.Color(252, 219, 225));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("CONFIRM THE ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1130, 200, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\cap (2).png")); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 120, -1));

        l1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l1.setText("jLabel25");
        jPanel2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 150, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\che (2).png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 970, 140, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\veg (2).png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\bbbaaaccckkk (1).png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        l444.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l444.setText("jLabel25");
        jPanel2.add(l444, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 730, -1, -1));

        l555.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l555.setText("jLabel25");
        jPanel2.add(l555, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 910, -1, -1));

        l44.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l44.setText("jLabel25");
        jPanel2.add(l44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, -1, -1));

        l666.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l666.setText("jLabel25");
        jPanel2.add(l666, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1080, -1, -1));

        l66.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l66.setText("jLabel25");
        jPanel2.add(l66, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1050, -1, -1));

        l55.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        l55.setText("jLabel25");
        jPanel2.add(l55, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 880, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\bbbaaaccckkk (1).png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, 520));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\CE_Diala\\3rd year\\DataBase\\cinema\\src\\pic\\bbbaaaccckkk (1).png")); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1000, -1, 200));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
 int x=1;
       s1.setValue(x);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        int x=1;
       s1.setValue(x);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
         int x=1;
       s1.setValue(x);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
         int x=1;
       s2.setValue(x); 
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
     int x=1;
       s2.setValue(x);    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
       int x=1;
       s2.setValue(x);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
int x=1;
       s3.setValue(x);         // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
       int x=1;
       s3.setValue(x);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
       int x=1;
       s3.setValue(x);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
       int x=1;
       s4.setValue(x);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
      int x=1;
       s4.setValue(x);    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
         int x=1;
       s4.setValue(x); // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        int x=1;
       s5.setValue(x);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
       int x=1;
       s5.setValue(x);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        int x=1;
       s5.setValue(x); // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        int x=1;
       s6.setValue(x); // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
           int x=1;
       s6.setValue(x);    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
             int x=1;
       s6.setValue(x);  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int ans;
        int n1,n2,n3,n4,n5,n6;
        
        n1=(int)s1.getValue();
        String n11=l1.getText();
       int n111=Integer.parseInt(n11);
       int n1111=n1*n111;
       
      
        String n110=l11.getText();
       int n1110=Integer.parseInt(n110);
       int n11110=n1*n1110;
       
         String n1100=l111.getText();
       int n11100=Integer.parseInt(n1100);
       int n111100=n1*n11100;
      ////////////////////////////////////////////// 
        n2=(int)s2.getValue();
         String n22=l2.getText();
       int n222=Integer.parseInt(n22);
       int n2222=n2*n222;
       
       String n220=l22.getText();
       int n2220=Integer.parseInt(n220);
       int n22220=n2*n2220;
       
        String n2200=l222.getText();
       int n22200=Integer.parseInt(n2200);
       int n222200=n2*n22200;
       
       ////////////////////////////////////////
       
        n3=(int)s3.getValue();
         String n33=l3.getText();
       int n333=Integer.parseInt(n33);
       int n3333=n3*n333;
       
       String n330=l33.getText();
       int n3330=Integer.parseInt(n330);
       int n33330=n3*n3330;
       
         String n3300=l333.getText();
       int n33300=Integer.parseInt(n3300);
       int n333300=n3*n33300; 
       ///////////////////////////////////////
       
        n4=(int)s4.getValue();
         String n44=l4.getText();
       int n444=Integer.parseInt(n44);
       int n4444=n4*n444;
       
        String n440=l44.getText();
       int n4440=Integer.parseInt(n440);
       int n44440=n4*n4440;
       
               String n4400=l444.getText();
       int n44400=Integer.parseInt(n4400);
       int n444400=n4*n44400;
       ///////////////////////////////////////
       
        n5=(int)s5.getValue();
         String n55=l5.getText();
       int n555=Integer.parseInt(n55);
       int n5555=n5*n555;
       
        String n550=l55.getText();
       int n5550=Integer.parseInt(n550);
       int n55550=n5*n5550;
       
       String n5500=l555.getText();
       int n55500=Integer.parseInt(n5500);
       int n555500=n5*n55500;
       ////////////////////////////////////
       
        n6=(int)s6.getValue();
         String n66=l6.getText();
       int n666=Integer.parseInt(n66);
       int n6666=n6*n666;
       
         String n660=l66.getText();
       int n6660=Integer.parseInt(n660);
       int n66660=n6*n6660;
       
          String n6600=l666.getText();
       int n66600=Integer.parseInt(n6600);
       int n666600=n6*n66600;
        
      
       //n1
        
          if(jRadioButton2.isSelected()&&jRadioButton1.isSelected()&&jRadioButton3.isSelected()){ans=(n1111+n111100+n11110); JOptionPane.showMessageDialog(null, ans);
        }
          else if(jRadioButton2.isSelected()&&jRadioButton3.isSelected()){ans=(n1111+n11110); JOptionPane.showMessageDialog(null, ans);
        }   
        else if(jRadioButton2.isSelected()&&jRadioButton1.isSelected()){ans=(n1111+n111100); JOptionPane.showMessageDialog(null, ans);
        } 
       else if(jRadioButton1.isSelected()&&jRadioButton3.isSelected()){ans=(n111100+n11110); JOptionPane.showMessageDialog(null, ans);
        }
      
       else if(jRadioButton2.isSelected()){ans=n1111; JOptionPane.showMessageDialog(null, ans);
        }
           else if(jRadioButton3.isSelected()){ans=n11110; JOptionPane.showMessageDialog(null, ans);
        }    
           else if(jRadioButton1.isSelected()){ans=n111100; JOptionPane.showMessageDialog(null, ans);
        }
////////////
       else if(jRadioButton4.isSelected()&&jRadioButton5.isSelected()&&jRadioButton6.isSelected()){ans=(n2222+n22220+n222200); JOptionPane.showMessageDialog(null, ans);
        }
        else if(jRadioButton4.isSelected()&&jRadioButton5.isSelected()){ans=(n2222+n22220); JOptionPane.showMessageDialog(null, ans);
         }
        else if(jRadioButton4.isSelected()&&jRadioButton6.isSelected()){ans=(n2222+n222200); JOptionPane.showMessageDialog(null, ans);
         }else if(jRadioButton5.isSelected()&&jRadioButton6.isSelected()){ans=(n22220+n222200); JOptionPane.showMessageDialog(null, ans);
         }
        else if(jRadioButton4.isSelected()){ans=n2222; JOptionPane.showMessageDialog(null, ans);
        }
          else  if(jRadioButton5.isSelected()){ans=n22220; JOptionPane.showMessageDialog(null, ans);
        } else   if(jRadioButton6.isSelected()){ans=n222200; JOptionPane.showMessageDialog(null, ans);
        }
                  ////////////
                if(jRadioButton7.isSelected()){ans=n3333; JOptionPane.showMessageDialog(null, ans);
        }
            if(jRadioButton8.isSelected()){ans=n33330; JOptionPane.showMessageDialog(null, ans);
        }    if(jRadioButton9.isSelected()){ans=n333300; JOptionPane.showMessageDialog(null, ans);
        }
                 ////////////
                 if(jRadioButton10.isSelected()){ans=n4444; JOptionPane.showMessageDialog(null, ans);
        }
             if(jRadioButton11.isSelected()){ans=n44440; JOptionPane.showMessageDialog(null, ans);
        }    if(jRadioButton12.isSelected()){ans=n444400; JOptionPane.showMessageDialog(null, ans);
        }
                  ////////////
                if(jRadioButton13.isSelected()){ans=n5555; JOptionPane.showMessageDialog(null, ans);
        }
             if(jRadioButton14.isSelected()){ans=n55550; JOptionPane.showMessageDialog(null, ans);
        }   if(jRadioButton15.isSelected()){ans=n555500; JOptionPane.showMessageDialog(null, ans);
        }////////////
                 if(jRadioButton16.isSelected()){ans=n6666; JOptionPane.showMessageDialog(null, ans);
        }
           if(jRadioButton17.isSelected()){ans=n66660; JOptionPane.showMessageDialog(null, ans);
        }    if(jRadioButton18.isSelected()){ans=n666600; JOptionPane.showMessageDialog(null, ans);
        }
      /*  ans=n1111+n2222+n3333+n4444+n5555+n6666+n11110+n22220+n33330+n44440+n55550+n66660;
      JOptionPane.showMessageDialog(null, ans);
        else if(n1==0&&n3==0&&n4==0&&n5==0&&n6==0){//n2
            ans=n2222; JOptionPane.showMessageDialog(null, ans);
        }else if(n2==0&&n1==0&&n4==0&&n5==0&&n6==0){//n3
            ans=n3333; JOptionPane.showMessageDialog(null, ans);
        }
        else if(n2==0&&n3==0&&n1==0&&n5==0&&n6==0){//n4
            ans=n4444; JOptionPane.showMessageDialog(null, ans);
        }else if(n2==0&&n3==0&&n4==0&&n1==0&&n6==0){//n5
            ans=n5555; JOptionPane.showMessageDialog(null, ans);
        }else if(n2==0&&n3==0&&n4==0&&n5==0&&n1==0){
            ans=n6666; JOptionPane.showMessageDialog(null, ans);
        }
      
     //   JOptionPane.showMessageDialog(null, ans);
      ans=n1111+n2222+n3333+n4444+n5555+n6666+n11110+n22220+n33330+n44440+n55550+n66660+n111100+n222200+n333300+n444400+n555500+n666600;
       JOptionPane.showMessageDialog(null, ans);  */                                    

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(piu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(piu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(piu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(piu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new piu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l111;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l222;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l333;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l44;
    private javax.swing.JLabel l444;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l55;
    private javax.swing.JLabel l555;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l66;
    private javax.swing.JLabel l666;
    private javax.swing.JSpinner s1;
    private javax.swing.JSpinner s2;
    private javax.swing.JSpinner s3;
    private javax.swing.JSpinner s4;
    private javax.swing.JSpinner s5;
    private javax.swing.JSpinner s6;
    // End of variables declaration//GEN-END:variables
}
